---

- name: Merge defaults with user variables.
  set_fact:
    system: "{{ system_defaults | combine(system, recursive=True) }}"
    finder: "{{ finder_defaults | combine(finder, recursive=True) }}"
    dock: "{{ dock_defaults | combine(dock, recursive=True) }}"
    safari: "{{ safari_defaults | combine(safari, recursive=True) }}"
    mail: "{{ mail_defaults | combine(mail, recursive=True) }}"
    textedit: "{{ textedit_defaults | combine(textedit, recursive=True) }}"
    terminal: "{{ terminal_defaults | combine(terminal, recursive=True) }}"
  tags: always

- import_tasks: system_input.yml
  tags: [system, input]

- import_tasks: system_ui.yml
  tags: [system, ui]

- import_tasks: system_security.yml
  tags: [system, security]

- import_tasks: system_misc.yml
  tags: [system, misc]

- import_tasks: system_pm.yml
  tags: [system, pm]

- import_tasks: system_screensaver.yml
  tags: [system, screensaver]

- import_tasks: system_hostname.yml
  tags: [system, hostname]

- import_tasks: system_default-applications.yml
  tags: [system, default-applications]

- import_tasks: finder.yml
  tags: [finder]

- import_tasks: dock.yml
  tags: [dock]

- import_tasks: safari.yml
  tags: [safari]

- import_tasks: mail.yml
  tags: [mail]

- import_tasks: terminal.yml
  tags: [terminal] 

- import_tasks: textedit.yml
  tags: [textedit]